CREATE ROLE flyway WITH LOGIN PASSWORD 'flywayPass';
ALTER ROLE flyway WITH CREATEDB;
ALTER ROLE flyway WITH SUPERUSER;

CREATE SCHEMA IF NOT EXISTS dwh AUTHORIZATION flyway;
CREATE SCHEMA IF NOT EXISTS dwh_source AUTHORIZATION flyway;

GRANT ALL PRIVILEGES ON SCHEMA dwh TO flyway;
GRANT ALL PRIVILEGES ON SCHEMA dwh_source TO flyway;
